README.md
I replaced the colons with dashes like on the other awesome repositories.
Then I added Trello, shortened the description of inbox0, added a description for habitRPG.
I hope you like it.
=> add Trello, Pomodoro; remove unneccessary stuff

CONTRIBUTING.md
Based on https://github.com/sindresorhus/awesome-nodejs/blob/master/contributing.md
=> Create CONTRIBUTING.md #2

README.md
I have added a couple of tools that I'm relying on.
Disclaimer: Since the book I've added requires a sign up to a mailing list, I should probably point out that I'm not connected to its owner in any way. I just enjoyed the book and I recommend it.
=> Adds a Todo.txt, Zappier and The Super Student Roadmap

README.md
Thank you for making great curated list!!
Please take a look :)
=> Add Inkdrop to "Note Management" section

README.md
Small tool for Windows to automate the Windows GUI, but it can also be used for other purposes.
=> Add AutoIt

README.md
I wrote topydo, a powerful todo.txt based application for the commandline.
Hereby my request to include the application on the list.
=> Add topydo to todo applications

README.md
=> Add a Habit Tracker app

README.md
Update task management category and sort alphabetically.
Add Hitask as a new task management software.
=> Update README.md and Add Hitask

README.md
=> Add VivifyScrum

README.md
Add productivity subreddit (r/productivity/) – https://www.reddit.com/r/productivity/.
=> Add productivity subreddit (r/productivity/)

README.md
=> Add KanbanFlow

README.md
The simplest way to keep notes.
=> Add Simplenote

README.md
I use it on SublimeText and I just know how much time I spend on each project.
=> Add wakatime to the list

README.md
Add Obie.ai to new Knowledge Management productivity category
=> Add Obie.ai

README.md
Screen capture, file sharing and productivity tool.
=> Add ShareX

README.md
Joplin is a free, open source note taking and to-do application, which can handle a large number of notes organised into notebooks. The notes are searchable, can be copied, tagged and modified either from the applications directly or from your own text editor. The notes are in Markdown format.
https://joplinapp.org/
https://github.com/laurent22/joplin
=> Add Joplin to Note Management

README.md
Nextcloud is an open source file sync and share application that offers free, secure, and easily accessible cloud file storage, as well as a number of tools that extend its feature set.
https://github.com/nextcloud
https://nextcloud.com/
=> Add Nextcloud to File Management

README.md
Spring Cleanup:
- Updated TOC
- Checked for dead links
- Reordered alphabetically
- Review current open PRs
=> 2021 sprint cleanup

README.md
Add Tinido to Task Management Tool section.
=> Add Tinido

README.md
Removed "web-based" from WorkFlowy, since there are desktop and mobile applications available.
Unified usage of app/application.
Corrected some words and capitalization.
=> Small corrections in Note Management section

README.md
Please refer this link for an extensive list of pros and cons:
https://www.slant.co/options/37045/~obsidian-md-review
=> Added Obsidian.md

README.md
Fixed a bunch of issue. See details #94
=> Awesome linting

README.md
=> adding Parabola automation tool

README.md
=> Update with new task management tool

README.md
[KeePass](https://keepass.info/)
A free, open source, light-weight password manager with auto-type, browser and plugin support.
=> Add "KeePass"

README.md
Added nordpass to password managers
=> feat: Add Nordpass to Password Managers

README.md
Updated the TOC to reflect the change from Misc to Screen Capture section
=> TOC Update

README.md
=> Add CleanShot

README.md
Hi @jyguyomarch!
I've added [Conjure](https://conjure.so) to the Habit Trackers section.
I looked at other PRs and added it in alphabetical order (which I understood to be the convention).
Thank you!
=> Add Conjure
